// Sample data for MOCK=1 mode: lets the dashboard run (and be demoed)
// without internet access. Shapes match the live normalizers exactly.

const hoursAgo = (h) => new Date(Date.now() - h * 3600 * 1000).toISOString();

export const MOCK_EVENTS = [
  {
    id: "usgs:mock-eq-japan",
    source: "USGS",
    type: "earthquake",
    title: "M 7.2 - 45 km E of Sendai, Japan",
    place: "45 km E of Sendai, Japan",
    severity: 3,
    magnitude: 7.2,
    lat: 38.26,
    lon: 141.5,
    time: hoursAgo(3),
    url: "https://earthquake.usgs.gov/",
  },
  {
    id: "gdacs:TC:mock-hurricane",
    source: "GDACS",
    type: "tropical cyclone",
    title: "Hurricane Odette headed for the Louisiana coast (Cat 3)",
    place: "United States",
    severity: 3,
    magnitude: null,
    lat: 27.8,
    lon: -90.2,
    time: hoursAgo(6),
    url: "https://www.gdacs.org/",
  },
  {
    id: "eonet:mock-wildfire",
    source: "NASA EONET",
    type: "wildfire",
    title: "Ridgeline Fire, Northern California",
    place: "California, United States",
    severity: 2,
    magnitude: null,
    lat: 39.7,
    lon: -121.6,
    time: hoursAgo(12),
    url: "https://eonet.gsfc.nasa.gov/",
  },
  {
    id: "gdacs:FL:mock-flood",
    source: "GDACS",
    type: "flood",
    title: "Severe monsoon flooding in Kerala",
    place: "India",
    severity: 2,
    magnitude: null,
    lat: 10.5,
    lon: 76.2,
    time: hoursAgo(20),
    url: "https://www.gdacs.org/",
  },
  {
    id: "eonet:mock-volcano",
    source: "NASA EONET",
    type: "volcano",
    title: "Mount Merapi eruption, Indonesia",
    place: "Indonesia",
    severity: 2,
    magnitude: null,
    lat: -7.54,
    lon: 110.44,
    time: hoursAgo(30),
    url: "https://eonet.gsfc.nasa.gov/",
  },
  {
    id: "usgs:mock-eq-minor",
    source: "USGS",
    type: "earthquake",
    title: "M 4.8 - South of the Fiji Islands",
    place: "South of the Fiji Islands",
    severity: 1,
    magnitude: 4.8,
    lat: -24.9,
    lon: 178.1,
    time: hoursAgo(1),
    url: "https://earthquake.usgs.gov/",
  },
];

export const MOCK_QUOTES = {
  "ALL.US": { symbol: "ALL.US", price: 186.4, changePct: -3.6 },
  "TRV.US": { symbol: "TRV.US", price: 232.1, changePct: -2.1 },
  "CB.US": { symbol: "CB.US", price: 268.9, changePct: -1.4 },
  "RNR.US": { symbol: "RNR.US", price: 241.3, changePct: -4.2 },
  "DAL.US": { symbol: "DAL.US", price: 44.2, changePct: -1.8 },
  "UAL.US": { symbol: "UAL.US", price: 51.7, changePct: -0.9 },
  "AAL.US": { symbol: "AAL.US", price: 11.9, changePct: -1.2 },
  "CCL.US": { symbol: "CCL.US", price: 17.8, changePct: -2.7 },
  "RCL.US": { symbol: "RCL.US", price: 148.6, changePct: -1.1 },
  "VLO.US": { symbol: "VLO.US", price: 139.2, changePct: -3.1 },
  "MPC.US": { symbol: "MPC.US", price: 172.4, changePct: -2.4 },
  "ETR.US": { symbol: "ETR.US", price: 118.9, changePct: -3.8 },
  "CNP.US": { symbol: "CNP.US", price: 30.1, changePct: -2.2 },
  "PCG.US": { symbol: "PCG.US", price: 17.2, changePct: -5.6 },
  "EIX.US": { symbol: "EIX.US", price: 68.4, changePct: -4.1 },
  "WY.US": { symbol: "WY.US", price: 28.9, changePct: -1.6 },
  "RYN.US": { symbol: "RYN.US", price: 27.3, changePct: -0.8 },
  "ADM.US": { symbol: "ADM.US", price: 53.6, changePct: -1.9 },
  "BG.US": { symbol: "BG.US", price: 91.2, changePct: -1.3 },
  "DBA.US": { symbol: "DBA.US", price: 26.4, changePct: 0.6 },
  "UNP.US": { symbol: "UNP.US", price: 224.7, changePct: -0.4 },
  "CSX.US": { symbol: "CSX.US", price: 33.5, changePct: -0.2 },
  "TSM.US": { symbol: "TSM.US", price: 184.2, changePct: -2.9 },
  "ZIM.US": { symbol: "ZIM.US", price: 16.8, changePct: -1.0 },
  "EWJ.US": { symbol: "EWJ.US", price: 71.9, changePct: -2.5 },
  "INDA.US": { symbol: "INDA.US", price: 53.4, changePct: -1.2 },
  "EIDO.US": { symbol: "EIDO.US", price: 21.6, changePct: -1.5 },
};
